/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as StudyAbroadIndexRouteImport } from './routes/study-abroad.index'
import { Route as OnlineUgProgramsIndexRouteImport } from './routes/online-ug-programs.index'
import { Route as OnlinePgProgramsIndexRouteImport } from './routes/online-pg-programs.index'
import { Route as StudyAbroadSlugRouteImport } from './routes/study-abroad.$slug'
import { Route as OnlineUgProgramsSlugRouteImport } from './routes/online-ug-programs.$slug'
import { Route as OnlinePgProgramsSlugRouteImport } from './routes/online-pg-programs.$slug'

const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadIndexRoute = StudyAbroadIndexRouteImport.update({
  id: '/study-abroad/',
  path: '/study-abroad/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineUgProgramsIndexRoute = OnlineUgProgramsIndexRouteImport.update({
  id: '/online-ug-programs/',
  path: '/online-ug-programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlinePgProgramsIndexRoute = OnlinePgProgramsIndexRouteImport.update({
  id: '/online-pg-programs/',
  path: '/online-pg-programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadSlugRoute = StudyAbroadSlugRouteImport.update({
  id: '/study-abroad/$slug',
  path: '/study-abroad/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineUgProgramsSlugRoute = OnlineUgProgramsSlugRouteImport.update({
  id: '/online-ug-programs/$slug',
  path: '/online-ug-programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlinePgProgramsSlugRoute = OnlinePgProgramsSlugRouteImport.update({
  id: '/online-pg-programs/$slug',
  path: '/online-pg-programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/online-pg-programs/$slug': typeof OnlinePgProgramsSlugRoute
  '/online-ug-programs/$slug': typeof OnlineUgProgramsSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
  '/online-pg-programs/': typeof OnlinePgProgramsIndexRoute
  '/online-ug-programs/': typeof OnlineUgProgramsIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/online-pg-programs/$slug': typeof OnlinePgProgramsSlugRoute
  '/online-ug-programs/$slug': typeof OnlineUgProgramsSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
  '/online-pg-programs': typeof OnlinePgProgramsIndexRoute
  '/online-ug-programs': typeof OnlineUgProgramsIndexRoute
  '/study-abroad': typeof StudyAbroadIndexRoute
  '/universities': typeof UniversitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/online-pg-programs/$slug': typeof OnlinePgProgramsSlugRoute
  '/online-ug-programs/$slug': typeof OnlineUgProgramsSlugRoute
  '/study-abroad/$slug': typeof StudyAbroadSlugRoute
  '/online-pg-programs/': typeof OnlinePgProgramsIndexRoute
  '/online-ug-programs/': typeof OnlineUgProgramsIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/online-pg-programs/$slug'
    | '/online-ug-programs/$slug'
    | '/study-abroad/$slug'
    | '/online-pg-programs/'
    | '/online-ug-programs/'
    | '/study-abroad/'
    | '/universities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/online-pg-programs/$slug'
    | '/online-ug-programs/$slug'
    | '/study-abroad/$slug'
    | '/online-pg-programs'
    | '/online-ug-programs'
    | '/study-abroad'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy-policy'
    | '/online-pg-programs/$slug'
    | '/online-ug-programs/$slug'
    | '/study-abroad/$slug'
    | '/online-pg-programs/'
    | '/online-ug-programs/'
    | '/study-abroad/'
    | '/universities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  OnlinePgProgramsSlugRoute: typeof OnlinePgProgramsSlugRoute
  OnlineUgProgramsSlugRoute: typeof OnlineUgProgramsSlugRoute
  StudyAbroadSlugRoute: typeof StudyAbroadSlugRoute
  OnlinePgProgramsIndexRoute: typeof OnlinePgProgramsIndexRoute
  OnlineUgProgramsIndexRoute: typeof OnlineUgProgramsIndexRoute
  StudyAbroadIndexRoute: typeof StudyAbroadIndexRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/': {
      id: '/study-abroad/'
      path: '/study-abroad'
      fullPath: '/study-abroad/'
      preLoaderRoute: typeof StudyAbroadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-ug-programs/': {
      id: '/online-ug-programs/'
      path: '/online-ug-programs'
      fullPath: '/online-ug-programs/'
      preLoaderRoute: typeof OnlineUgProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-pg-programs/': {
      id: '/online-pg-programs/'
      path: '/online-pg-programs'
      fullPath: '/online-pg-programs/'
      preLoaderRoute: typeof OnlinePgProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/$slug': {
      id: '/study-abroad/$slug'
      path: '/study-abroad/$slug'
      fullPath: '/study-abroad/$slug'
      preLoaderRoute: typeof StudyAbroadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-ug-programs/$slug': {
      id: '/online-ug-programs/$slug'
      path: '/online-ug-programs/$slug'
      fullPath: '/online-ug-programs/$slug'
      preLoaderRoute: typeof OnlineUgProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-pg-programs/$slug': {
      id: '/online-pg-programs/$slug'
      path: '/online-pg-programs/$slug'
      fullPath: '/online-pg-programs/$slug'
      preLoaderRoute: typeof OnlinePgProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  OnlinePgProgramsSlugRoute: OnlinePgProgramsSlugRoute,
  OnlineUgProgramsSlugRoute: OnlineUgProgramsSlugRoute,
  StudyAbroadSlugRoute: StudyAbroadSlugRoute,
  OnlinePgProgramsIndexRoute: OnlinePgProgramsIndexRoute,
  OnlineUgProgramsIndexRoute: OnlineUgProgramsIndexRoute,
  StudyAbroadIndexRoute: StudyAbroadIndexRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
