/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnlineUgProgramsIndexRouteImport } from './routes/online-ug-programs.index'
import { Route as OnlinePgProgramsIndexRouteImport } from './routes/online-pg-programs.index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineUgProgramsIndexRoute = OnlineUgProgramsIndexRouteImport.update({
  id: '/online-ug-programs/',
  path: '/online-ug-programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlinePgProgramsIndexRoute = OnlinePgProgramsIndexRouteImport.update({
  id: '/online-pg-programs/',
  path: '/online-pg-programs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/online-pg-programs/': typeof OnlinePgProgramsIndexRoute
  '/online-ug-programs/': typeof OnlineUgProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/online-pg-programs': typeof OnlinePgProgramsIndexRoute
  '/online-ug-programs': typeof OnlineUgProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/online-pg-programs/': typeof OnlinePgProgramsIndexRoute
  '/online-ug-programs/': typeof OnlineUgProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/online-pg-programs/' | '/online-ug-programs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/online-pg-programs' | '/online-ug-programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/online-pg-programs/'
    | '/online-ug-programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OnlinePgProgramsIndexRoute: typeof OnlinePgProgramsIndexRoute
  OnlineUgProgramsIndexRoute: typeof OnlineUgProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-ug-programs/': {
      id: '/online-ug-programs/'
      path: '/online-ug-programs'
      fullPath: '/online-ug-programs/'
      preLoaderRoute: typeof OnlineUgProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-pg-programs/': {
      id: '/online-pg-programs/'
      path: '/online-pg-programs'
      fullPath: '/online-pg-programs/'
      preLoaderRoute: typeof OnlinePgProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OnlinePgProgramsIndexRoute: OnlinePgProgramsIndexRoute,
  OnlineUgProgramsIndexRoute: OnlineUgProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
